"""Add constraint configuration table

Revision ID: 0e7c35911403
Revises: 1fddf9390bbc
Create Date: 2025-12-09 20:09:24.605874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7c35911403'
down_revision: Union[str, None] = '1fddf9390bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraint_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('timeslot_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('days_per_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('hard_constraints', sa.JSON(), nullable=True),
    sa.Column('soft_constraints', sa.JSON(), nullable=True),
    sa.Column('optional_constraints', sa.JSON(), nullable=True),
    sa.Column('max_optimization_time_seconds', sa.Integer(), nullable=True),
    sa.Column('min_acceptable_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constraint_configs_id'), 'constraint_configs', ['id'], unique=False)
    op.create_index(op.f('ix_constraint_configs_institution_id'), 'constraint_configs', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_constraint_configs_institution_id'), table_name='constraint_configs')
    op.drop_index(op.f('ix_constraint_configs_id'), table_name='constraint_configs')
    op.drop_table('constraint_configs')
    # ### end Alembic commands ###
