"""add_teacher_constraint_profiles

Revision ID: b197187e30c2
Revises: 2f8d46a92514
Create Date: 2025-12-22 19:06:57.930723

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import inspect
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b197187e30c2'
down_revision: Union[str, None] = '2f8d46a92514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_constraint_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_constraint_profiles_id'), 'teacher_constraint_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_constraint_profiles_institution_id'), 'teacher_constraint_profiles', ['institution_id'], unique=False)
    op.create_table('teacher_constraint_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('constraint_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['teacher_constraint_profiles.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_constraint_items_id'), 'teacher_constraint_items', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_constraint_items_profile_id'), 'teacher_constraint_items', ['profile_id'], unique=False)

    # Handle 'program' column on courses table idempotently
    # The column was missing from initial migration but exists in the model
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("courses")]

    if "program" not in columns:
        # Column doesn't exist - add it with the correct type
        op.add_column('courses', sa.Column('program', sa.String(length=100), nullable=True))
    else:
        # Column exists - alter it to ensure correct type
        op.alter_column('courses', 'program',
                   existing_type=sa.VARCHAR(length=255),
                   type_=sa.String(length=100),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Handle 'program' column downgrade idempotently
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("courses")]

    if "program" in columns:
        # If column was added by this migration (fresh DB), drop it
        # If column existed before (local DB), revert type change
        # For safety, we revert the type - dropping would lose data
        op.alter_column('courses', 'program',
                   existing_type=sa.String(length=100),
                   type_=sa.VARCHAR(length=255),
                   existing_nullable=True)

    op.drop_index(op.f('ix_teacher_constraint_items_profile_id'), table_name='teacher_constraint_items')
    op.drop_index(op.f('ix_teacher_constraint_items_id'), table_name='teacher_constraint_items')
    op.drop_table('teacher_constraint_items')
    op.drop_index(op.f('ix_teacher_constraint_profiles_institution_id'), table_name='teacher_constraint_profiles')
    op.drop_index(op.f('ix_teacher_constraint_profiles_id'), table_name='teacher_constraint_profiles')
    op.drop_table('teacher_constraint_profiles')
    # ### end Alembic commands ###
